set_property SRC_FILE_INFO {cfile:C:/Users/CK/Downloads/IP_proj_0107/IP_proj.srcs/constrs_1/imports/IP_proj_1127/lab3_system.xdc rfile:../../../IP_proj.srcs/constrs_1/imports/IP_proj_1127/lab3_system.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14     [get_ports  LED[0]]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13     [get_ports  LED[1]]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13     [get_ports  LED[2]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14     [get_ports  LED[3]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15     [get_ports  LED[4]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13     [get_ports  LED[5]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14     [get_ports  LED[6]]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL12     [get_ports  LED[7]]
